package com.caffeaulait.dianping.model;

public class RecommendDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.id
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recommend.shops
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    private String shops;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.id
     *
     * @return the value of recommend.id
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.id
     *
     * @param id the value for recommend.id
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recommend.shops
     *
     * @return the value of recommend.shops
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    public String getShops() {
        return shops;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recommend.shops
     *
     * @param shops the value for recommend.shops
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    public void setShops(String shops) {
        this.shops = shops == null ? null : shops.trim();
    }
}