package com.caffeaulait.dianping.dao;

import com.caffeaulait.dianping.model.RecommendDO;
import org.springframework.stereotype.Repository;

@Repository
public interface RecommendDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    int insert(RecommendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    int insertSelective(RecommendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    RecommendDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    int updateByPrimaryKeySelective(RecommendDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Sun Jun 20 15:06:31 CST 2021
     */
    int updateByPrimaryKey(RecommendDO record);
}