package com.caffeaulait.dianping.dao;

import com.caffeaulait.dianping.model.Seller;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SellerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Sun Jun 13 16:52:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Sun Jun 13 16:52:14 CST 2021
     */
    int insert(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Sun Jun 13 16:52:14 CST 2021
     */
    int insertSelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Sun Jun 13 16:52:14 CST 2021
     */
    Seller selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Sun Jun 13 16:52:14 CST 2021
     */
    int updateByPrimaryKeySelective(Seller record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller
     *
     * @mbg.generated Sun Jun 13 16:52:14 CST 2021
     */
    int updateByPrimaryKey(Seller record);

    List<Seller> selectAll();

    Integer countAll();
}